version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.app
      - FLASK_ENV=production
      - SECRET_KEY=your_production_secret_key
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
